joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

# Position Controllers ---------------------------------------
joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_1
    pid: {p: 2000.0, i: 100, d: 500.0}
joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_2
    pid: {p: 50000.0, i: 100, d: 2000.0}
joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_link__link_01
    pid: {p: 20000.0, i: 50, d: 1000.0} 
      